### ISSUE TITLE
Update to Duktape 2.6.0

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/duktape-android#177]
Just released

**Comment by oldergod** [comment]
We're not using quickJs from now on?

**Comment by JakeWharton** [comment]
Both are in the repo currently. QuickJS needs to soak before we can make the switch. I'm not sure how others feel. If we can keep Duktape up-to-date easily, though, I don't mind doing that in the mean time. Currently I'm spending 0% time on this but I'm hoping to raise it to 1-2% in a month or two.

**Comment by EyalDagiAvdor** [comment]
Sorry for a trivial question but how do I get the new version of duktape through gradle?
In the download section it mentions. 
`compile 'com.squareup.duktape:duktape-android:1.3.0' `
Updating to 2.6.0 fails to resolve.

**Comment by JakeWharton** [comment]
The versioning of this library is different from Duktape proper and we have not yet updated to use Duktape 2.6.0. Whatever is in the README is the latest.

**Comment by parahall** [comment]
Bump :) Do you plan to update it to the latest Duktape in any observable future? :) Thanks a lot)
